### PR TITLE
Add delete() method to BigCommerceCustomersAPI

### PR DESCRIPTION
**Pull request by r-thomson**
Add support for deleting customers.

https://developer.bigcommerce.com/api-reference/e6bb04315e2a7-delete-customers

### CODE REVIEW

**Review by fieryprophet — COMMENTED** [review]
I've noticed elsewhere in this package we return the result from the API deletion call for other resources, should we do here as well for consistency?

**Review by Iapetus-11 — CHANGES_REQUESTED** [review]
It looks like this endpoint supports bulk deletion, perhaps that should be supported? https://developer.bigcommerce.com/api-reference/e6bb04315e2a7-delete-customers

**Comment by r-thomson** [comment]
> It looks like this endpoint supports bulk deletion, perhaps that should be supported?

We don't have a standard pattern right now for bulk actions, so we don't support it.

**Review by Iapetus-11 — APPROVED** [review]

**Comment by r-thomson** [comment]
> I've noticed elsewhere in this package we return the result from the API deletion call for other resources, should we do here as well for consistency?

There is no result from the API (HTTP 204)

**Review by maxheyn — APPROVED** [review]

**Review by fieryprophet — APPROVED** [review]

**Pull request merged**
